/********************************************************************************
** Form generated from reading UI file 'layerproperties.ui'
**
** Created: Wed Apr 29 21:05:23 2015
**      by: Qt User Interface Compiler version 4.8.1
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_LAYERPROPERTIES_H
#define UI_LAYERPROPERTIES_H

#include <QtCore/QVariant>
#include <QtGui/QAction>
#include <QtGui/QApplication>
#include <QtGui/QButtonGroup>
#include <QtGui/QCheckBox>
#include <QtGui/QComboBox>
#include <QtGui/QDialog>
#include <QtGui/QDialogButtonBox>
#include <QtGui/QGridLayout>
#include <QtGui/QGroupBox>
#include <QtGui/QHBoxLayout>
#include <QtGui/QHeaderView>
#include <QtGui/QLabel>
#include <QtGui/QLineEdit>
#include <QtGui/QListView>
#include <QtGui/QListWidget>
#include <QtGui/QPushButton>
#include <QtGui/QScrollArea>
#include <QtGui/QSlider>
#include <QtGui/QSpacerItem>
#include <QtGui/QSpinBox>
#include <QtGui/QSplitter>
#include <QtGui/QStackedWidget>
#include <QtGui/QTabWidget>
#include <QtGui/QTextEdit>
#include <QtGui/QWidget>

QT_BEGIN_NAMESPACE

class Ui_LayerProperties
{
public:
    QListWidget *listWidget;
    QStackedWidget *stackedWidget;
    QWidget *generalPage;
    QGridLayout *gridLayout;
    QGroupBox *groupBox;
    QLabel *label;
    QLineEdit *lineEdit;
    QLabel *label_2;
    QLineEdit *lineEdit_2;
    QLabel *label_25;
    QLineEdit *lineEdit_4;
    QLabel *label_26;
    QLineEdit *lineEdit_5;
    QCheckBox *checkBox;
    QSplitter *splitter_7;
    QLabel *label_27;
    QComboBox *comboBox_6;
    QSplitter *splitter_8;
    QLabel *label_28;
    QComboBox *comboBox_7;
    QWidget *stylePage;
    QGridLayout *gridLayout_3;
    QGroupBox *groupBox_2;
    QWidget *widget;
    QLabel *label_3;
    QLabel *label_4;
    QSlider *horizontalSlider;
    QLabel *label_5;
    QComboBox *comboBox;
    QScrollArea *scrollArea;
    QWidget *scrollAreaWidgetContents;
    QLabel *label_6;
    QWidget *labelPage;
    QGridLayout *gridLayout_4;
    QGroupBox *groupBox_3;
    QLineEdit *lineEdit_3;
    QPushButton *pushButton;
    QStackedWidget *stackedWidget_2;
    QWidget *textPage;
    QLabel *label_9;
    QLabel *label_16;
    QComboBox *comboBox_2;
    QLabel *label_17;
    QComboBox *comboBox_3;
    QLabel *label_18;
    QSpinBox *spinBox;
    QLabel *label_19;
    QComboBox *comboBox_4;
    QLabel *label_20;
    QSlider *horizontalSlider_2;
    QLabel *label_21;
    QComboBox *comboBox_5;
    QSplitter *splitter_31;
    QSplitter *splitter_29;
    QLabel *label_23;
    QSpinBox *spinBox_2;
    QSplitter *splitter_30;
    QLabel *label_24;
    QSpinBox *spinBox_3;
    QLabel *label_22;
    QWidget *formatingPage;
    QLabel *label_10;
    QLabel *label_30;
    QCheckBox *checkBox_2;
    QLabel *label_31;
    QSpinBox *spinBox_4;
    QLabel *label_32;
    QComboBox *comboBox_9;
    QLabel *label_33;
    QSpinBox *spinBox_5;
    QWidget *bufferPage;
    QLabel *label_11;
    QCheckBox *checkBox_3;
    QSpinBox *spinBox_13;
    QLabel *label_34;
    QLabel *label_36;
    QSlider *horizontalSlider_3;
    QLabel *label_35;
    QComboBox *comboBox_11;
    QWidget *backgroundPage;
    QLabel *label_12;
    QCheckBox *checkBox_4;
    QLabel *label_38;
    QComboBox *comboBox_12;
    QLabel *label_39;
    QSpinBox *spinBox_6;
    QSpinBox *spinBox_7;
    QLabel *label_40;
    QSlider *horizontalSlider_4;
    QLabel *label_41;
    QComboBox *comboBox_13;
    QLabel *label_42;
    QComboBox *comboBox_14;
    QLabel *label_43;
    QSpinBox *spinBox_8;
    QWidget *shadowPage;
    QLabel *label_13;
    QCheckBox *checkBox_5;
    QLabel *label_37;
    QComboBox *comboBox_15;
    QLabel *label_44;
    QSpinBox *spinBox_10;
    QLabel *label_45;
    QSpinBox *spinBox_11;
    QLabel *label_46;
    QSlider *horizontalSlider_5;
    QLabel *label_47;
    QSpinBox *spinBox_9;
    QLabel *label_48;
    QComboBox *comboBox_16;
    QListWidget *listWidget_2;
    QLabel *label_8;
    QLabel *label_29;
    QComboBox *comboBox_8;
    QSplitter *splitter_19;
    QLabel *label_7;
    QTextEdit *textEdit;
    QWidget *diagramPage;
    QGridLayout *gridLayout_5;
    QGroupBox *groupBox_4;
    QCheckBox *checkBox_6;
    QLabel *label_14;
    QComboBox *comboBox_17;
    QTabWidget *tabWidget;
    QWidget *Appearance;
    QPushButton *pushButton_2;
    QLabel *label_15;
    QSlider *horizontalSlider_6;
    QLabel *label_49;
    QComboBox *comboBox_18;
    QLabel *label_50;
    QComboBox *comboBox_19;
    QLabel *label_51;
    QComboBox *comboBox_20;
    QWidget *Size;
    QCheckBox *checkBox_7;
    QSpinBox *spinBox_12;
    QWidget *Position;
    QCheckBox *checkBox_8;
    QSplitter *splitter_57;
    QLabel *label_55;
    QComboBox *comboBox_24;
    QSplitter *splitter_58;
    QLabel *label_54;
    QComboBox *comboBox_23;
    QLabel *label_52;
    QComboBox *comboBox_21;
    QLabel *label_53;
    QComboBox *comboBox_22;
    QListView *listView;
    QListView *listView_2;
    QPushButton *pushButton_3;
    QPushButton *pushButton_4;
    QLabel *label_56;
    QLabel *label_57;
    QWidget *defaultStylePage;
    QGridLayout *gridLayout_6;
    QGroupBox *groupBox_5;
    QLabel *label_58;
    QLabel *label_63;
    QLabel *label_64;
    QSlider *horizontalSlider_7;
    QCheckBox *checkBox_9;
    QLabel *label_59;
    QComboBox *comboBox_25;
    QLabel *label_62;
    QComboBox *comboBox_28;
    QLabel *label_60;
    QComboBox *comboBox_26;
    QLabel *label_61;
    QComboBox *comboBox_27;
    QWidget *layoutWidget;
    QHBoxLayout *horizontalLayout_7;
    QSpacerItem *horizontalSpacer_5;
    QDialogButtonBox *buttonBox;

    void setupUi(QDialog *LayerProperties)
    {
        if (LayerProperties->objectName().isEmpty())
            LayerProperties->setObjectName(QString::fromUtf8("LayerProperties"));
        LayerProperties->resize(668, 495);
        listWidget = new QListWidget(LayerProperties);
        new QListWidgetItem(listWidget);
        new QListWidgetItem(listWidget);
        new QListWidgetItem(listWidget);
        new QListWidgetItem(listWidget);
        new QListWidgetItem(listWidget);
        listWidget->setObjectName(QString::fromUtf8("listWidget"));
        listWidget->setGeometry(QRect(9, 9, 121, 477));
        stackedWidget = new QStackedWidget(LayerProperties);
        stackedWidget->setObjectName(QString::fromUtf8("stackedWidget"));
        stackedWidget->setGeometry(QRect(130, 10, 531, 451));
        generalPage = new QWidget();
        generalPage->setObjectName(QString::fromUtf8("generalPage"));
        gridLayout = new QGridLayout(generalPage);
        gridLayout->setObjectName(QString::fromUtf8("gridLayout"));
        groupBox = new QGroupBox(generalPage);
        groupBox->setObjectName(QString::fromUtf8("groupBox"));
        groupBox->setMouseTracking(false);
        groupBox->setFlat(false);
        groupBox->setCheckable(false);
        label = new QLabel(groupBox);
        label->setObjectName(QString::fromUtf8("label"));
        label->setGeometry(QRect(20, 30, 57, 16));
        lineEdit = new QLineEdit(groupBox);
        lineEdit->setObjectName(QString::fromUtf8("lineEdit"));
        lineEdit->setGeometry(QRect(170, 30, 311, 20));
        label_2 = new QLabel(groupBox);
        label_2->setObjectName(QString::fromUtf8("label_2"));
        label_2->setGeometry(QRect(20, 60, 63, 16));
        lineEdit_2 = new QLineEdit(groupBox);
        lineEdit_2->setObjectName(QString::fromUtf8("lineEdit_2"));
        lineEdit_2->setGeometry(QRect(170, 60, 311, 20));
        label_25 = new QLabel(groupBox);
        label_25->setObjectName(QString::fromUtf8("label_25"));
        label_25->setGeometry(QRect(20, 90, 54, 16));
        lineEdit_4 = new QLineEdit(groupBox);
        lineEdit_4->setObjectName(QString::fromUtf8("lineEdit_4"));
        lineEdit_4->setGeometry(QRect(170, 90, 311, 20));
        label_26 = new QLabel(groupBox);
        label_26->setObjectName(QString::fromUtf8("label_26"));
        label_26->setGeometry(QRect(20, 120, 144, 16));
        lineEdit_5 = new QLineEdit(groupBox);
        lineEdit_5->setObjectName(QString::fromUtf8("lineEdit_5"));
        lineEdit_5->setGeometry(QRect(174, 120, 301, 20));
        checkBox = new QCheckBox(groupBox);
        checkBox->setObjectName(QString::fromUtf8("checkBox"));
        checkBox->setGeometry(QRect(20, 170, 143, 17));
        splitter_7 = new QSplitter(groupBox);
        splitter_7->setObjectName(QString::fromUtf8("splitter_7"));
        splitter_7->setGeometry(QRect(40, 200, 171, 21));
        splitter_7->setOrientation(Qt::Horizontal);
        label_27 = new QLabel(splitter_7);
        label_27->setObjectName(QString::fromUtf8("label_27"));
        splitter_7->addWidget(label_27);
        comboBox_6 = new QComboBox(splitter_7);
        comboBox_6->setObjectName(QString::fromUtf8("comboBox_6"));
        splitter_7->addWidget(comboBox_6);
        splitter_8 = new QSplitter(groupBox);
        splitter_8->setObjectName(QString::fromUtf8("splitter_8"));
        splitter_8->setGeometry(QRect(40, 230, 171, 21));
        splitter_8->setOrientation(Qt::Horizontal);
        label_28 = new QLabel(splitter_8);
        label_28->setObjectName(QString::fromUtf8("label_28"));
        splitter_8->addWidget(label_28);
        comboBox_7 = new QComboBox(splitter_8);
        comboBox_7->setObjectName(QString::fromUtf8("comboBox_7"));
        splitter_8->addWidget(comboBox_7);

        gridLayout->addWidget(groupBox, 0, 1, 1, 1);

        stackedWidget->addWidget(generalPage);
        stylePage = new QWidget();
        stylePage->setObjectName(QString::fromUtf8("stylePage"));
        gridLayout_3 = new QGridLayout(stylePage);
        gridLayout_3->setObjectName(QString::fromUtf8("gridLayout_3"));
        groupBox_2 = new QGroupBox(stylePage);
        groupBox_2->setObjectName(QString::fromUtf8("groupBox_2"));
        widget = new QWidget(groupBox_2);
        widget->setObjectName(QString::fromUtf8("widget"));
        widget->setGeometry(QRect(110, 20, 161, 91));
        widget->setAutoFillBackground(true);
        label_3 = new QLabel(groupBox_2);
        label_3->setObjectName(QString::fromUtf8("label_3"));
        label_3->setGeometry(QRect(19, 27, 51, 16));
        label_4 = new QLabel(groupBox_2);
        label_4->setObjectName(QString::fromUtf8("label_4"));
        label_4->setGeometry(QRect(20, 130, 66, 16));
        horizontalSlider = new QSlider(groupBox_2);
        horizontalSlider->setObjectName(QString::fromUtf8("horizontalSlider"));
        horizontalSlider->setGeometry(QRect(110, 130, 361, 19));
        horizontalSlider->setOrientation(Qt::Horizontal);
        label_5 = new QLabel(groupBox_2);
        label_5->setObjectName(QString::fromUtf8("label_5"));
        label_5->setGeometry(QRect(20, 160, 31, 16));
        comboBox = new QComboBox(groupBox_2);
        comboBox->setObjectName(QString::fromUtf8("comboBox"));
        comboBox->setGeometry(QRect(110, 160, 111, 20));
        scrollArea = new QScrollArea(groupBox_2);
        scrollArea->setObjectName(QString::fromUtf8("scrollArea"));
        scrollArea->setGeometry(QRect(110, 200, 161, 101));
        scrollArea->setWidgetResizable(true);
        scrollAreaWidgetContents = new QWidget();
        scrollAreaWidgetContents->setObjectName(QString::fromUtf8("scrollAreaWidgetContents"));
        scrollAreaWidgetContents->setGeometry(QRect(0, 0, 159, 99));
        scrollArea->setWidget(scrollAreaWidgetContents);
        label_6 = new QLabel(groupBox_2);
        label_6->setObjectName(QString::fromUtf8("label_6"));
        label_6->setGeometry(QRect(20, 200, 71, 16));

        gridLayout_3->addWidget(groupBox_2, 0, 1, 1, 1);

        stackedWidget->addWidget(stylePage);
        labelPage = new QWidget();
        labelPage->setObjectName(QString::fromUtf8("labelPage"));
        gridLayout_4 = new QGridLayout(labelPage);
        gridLayout_4->setObjectName(QString::fromUtf8("gridLayout_4"));
        groupBox_3 = new QGroupBox(labelPage);
        groupBox_3->setObjectName(QString::fromUtf8("groupBox_3"));
        lineEdit_3 = new QLineEdit(groupBox_3);
        lineEdit_3->setObjectName(QString::fromUtf8("lineEdit_3"));
        lineEdit_3->setGeometry(QRect(130, 110, 331, 21));
        pushButton = new QPushButton(groupBox_3);
        pushButton->setObjectName(QString::fromUtf8("pushButton"));
        pushButton->setGeometry(QRect(460, 110, 31, 21));
        stackedWidget_2 = new QStackedWidget(groupBox_3);
        stackedWidget_2->setObjectName(QString::fromUtf8("stackedWidget_2"));
        stackedWidget_2->setGeometry(QRect(120, 150, 371, 261));
        textPage = new QWidget();
        textPage->setObjectName(QString::fromUtf8("textPage"));
        label_9 = new QLabel(textPage);
        label_9->setObjectName(QString::fromUtf8("label_9"));
        label_9->setGeometry(QRect(10, 0, 91, 16));
        QFont font;
        font.setBold(true);
        font.setWeight(75);
        label_9->setFont(font);
        label_16 = new QLabel(textPage);
        label_16->setObjectName(QString::fromUtf8("label_16"));
        label_16->setGeometry(QRect(20, 30, 22, 16));
        comboBox_2 = new QComboBox(textPage);
        comboBox_2->setObjectName(QString::fromUtf8("comboBox_2"));
        comboBox_2->setGeometry(QRect(90, 30, 131, 20));
        label_17 = new QLabel(textPage);
        label_17->setObjectName(QString::fromUtf8("label_17"));
        label_17->setGeometry(QRect(20, 58, 24, 16));
        comboBox_3 = new QComboBox(textPage);
        comboBox_3->setObjectName(QString::fromUtf8("comboBox_3"));
        comboBox_3->setGeometry(QRect(90, 60, 131, 20));
        label_18 = new QLabel(textPage);
        label_18->setObjectName(QString::fromUtf8("label_18"));
        label_18->setGeometry(QRect(20, 90, 19, 16));
        spinBox = new QSpinBox(textPage);
        spinBox->setObjectName(QString::fromUtf8("spinBox"));
        spinBox->setGeometry(QRect(90, 90, 131, 20));
        label_19 = new QLabel(textPage);
        label_19->setObjectName(QString::fromUtf8("label_19"));
        label_19->setGeometry(QRect(20, 120, 31, 16));
        comboBox_4 = new QComboBox(textPage);
        comboBox_4->setObjectName(QString::fromUtf8("comboBox_4"));
        comboBox_4->setGeometry(QRect(90, 120, 131, 20));
        label_20 = new QLabel(textPage);
        label_20->setObjectName(QString::fromUtf8("label_20"));
        label_20->setGeometry(QRect(20, 150, 66, 16));
        horizontalSlider_2 = new QSlider(textPage);
        horizontalSlider_2->setObjectName(QString::fromUtf8("horizontalSlider_2"));
        horizontalSlider_2->setGeometry(QRect(90, 150, 261, 19));
        horizontalSlider_2->setOrientation(Qt::Horizontal);
        label_21 = new QLabel(textPage);
        label_21->setObjectName(QString::fromUtf8("label_21"));
        label_21->setGeometry(QRect(20, 180, 51, 16));
        comboBox_5 = new QComboBox(textPage);
        comboBox_5->setObjectName(QString::fromUtf8("comboBox_5"));
        comboBox_5->setGeometry(QRect(90, 180, 131, 20));
        splitter_31 = new QSplitter(textPage);
        splitter_31->setObjectName(QString::fromUtf8("splitter_31"));
        splitter_31->setGeometry(QRect(90, 210, 131, 40));
        splitter_31->setOrientation(Qt::Vertical);
        splitter_29 = new QSplitter(splitter_31);
        splitter_29->setObjectName(QString::fromUtf8("splitter_29"));
        splitter_29->setOrientation(Qt::Horizontal);
        label_23 = new QLabel(splitter_29);
        label_23->setObjectName(QString::fromUtf8("label_23"));
        splitter_29->addWidget(label_23);
        spinBox_2 = new QSpinBox(splitter_29);
        spinBox_2->setObjectName(QString::fromUtf8("spinBox_2"));
        splitter_29->addWidget(spinBox_2);
        splitter_31->addWidget(splitter_29);
        splitter_30 = new QSplitter(splitter_31);
        splitter_30->setObjectName(QString::fromUtf8("splitter_30"));
        splitter_30->setOrientation(Qt::Horizontal);
        label_24 = new QLabel(splitter_30);
        label_24->setObjectName(QString::fromUtf8("label_24"));
        splitter_30->addWidget(label_24);
        spinBox_3 = new QSpinBox(splitter_30);
        spinBox_3->setObjectName(QString::fromUtf8("spinBox_3"));
        splitter_30->addWidget(spinBox_3);
        splitter_31->addWidget(splitter_30);
        label_22 = new QLabel(textPage);
        label_22->setObjectName(QString::fromUtf8("label_22"));
        label_22->setGeometry(QRect(20, 210, 37, 16));
        stackedWidget_2->addWidget(textPage);
        formatingPage = new QWidget();
        formatingPage->setObjectName(QString::fromUtf8("formatingPage"));
        label_10 = new QLabel(formatingPage);
        label_10->setObjectName(QString::fromUtf8("label_10"));
        label_10->setGeometry(QRect(10, 0, 131, 16));
        label_10->setFont(font);
        label_30 = new QLabel(formatingPage);
        label_30->setObjectName(QString::fromUtf8("label_30"));
        label_30->setGeometry(QRect(20, 30, 111, 17));
        checkBox_2 = new QCheckBox(formatingPage);
        checkBox_2->setObjectName(QString::fromUtf8("checkBox_2"));
        checkBox_2->setGeometry(QRect(20, 130, 161, 22));
        label_31 = new QLabel(formatingPage);
        label_31->setObjectName(QString::fromUtf8("label_31"));
        label_31->setGeometry(QRect(20, 60, 53, 16));
        spinBox_4 = new QSpinBox(formatingPage);
        spinBox_4->setObjectName(QString::fromUtf8("spinBox_4"));
        spinBox_4->setGeometry(QRect(90, 60, 111, 20));
        label_32 = new QLabel(formatingPage);
        label_32->setObjectName(QString::fromUtf8("label_32"));
        label_32->setGeometry(QRect(20, 90, 47, 16));
        comboBox_9 = new QComboBox(formatingPage);
        comboBox_9->setObjectName(QString::fromUtf8("comboBox_9"));
        comboBox_9->setGeometry(QRect(90, 90, 111, 20));
        label_33 = new QLabel(formatingPage);
        label_33->setObjectName(QString::fromUtf8("label_33"));
        label_33->setGeometry(QRect(40, 160, 69, 16));
        spinBox_5 = new QSpinBox(formatingPage);
        spinBox_5->setObjectName(QString::fromUtf8("spinBox_5"));
        spinBox_5->setGeometry(QRect(123, 160, 81, 20));
        stackedWidget_2->addWidget(formatingPage);
        bufferPage = new QWidget();
        bufferPage->setObjectName(QString::fromUtf8("bufferPage"));
        label_11 = new QLabel(bufferPage);
        label_11->setObjectName(QString::fromUtf8("label_11"));
        label_11->setGeometry(QRect(10, 0, 91, 16));
        label_11->setFont(font);
        checkBox_3 = new QCheckBox(bufferPage);
        checkBox_3->setObjectName(QString::fromUtf8("checkBox_3"));
        checkBox_3->setGeometry(QRect(10, 30, 151, 22));
        spinBox_13 = new QSpinBox(bufferPage);
        spinBox_13->setObjectName(QString::fromUtf8("spinBox_13"));
        spinBox_13->setGeometry(QRect(110, 60, 81, 22));
        label_34 = new QLabel(bufferPage);
        label_34->setObjectName(QString::fromUtf8("label_34"));
        label_34->setGeometry(QRect(30, 60, 19, 16));
        label_36 = new QLabel(bufferPage);
        label_36->setObjectName(QString::fromUtf8("label_36"));
        label_36->setGeometry(QRect(30, 130, 66, 16));
        horizontalSlider_3 = new QSlider(bufferPage);
        horizontalSlider_3->setObjectName(QString::fromUtf8("horizontalSlider_3"));
        horizontalSlider_3->setGeometry(QRect(110, 130, 241, 20));
        horizontalSlider_3->setOrientation(Qt::Horizontal);
        label_35 = new QLabel(bufferPage);
        label_35->setObjectName(QString::fromUtf8("label_35"));
        label_35->setGeometry(QRect(30, 100, 25, 16));
        comboBox_11 = new QComboBox(bufferPage);
        comboBox_11->setObjectName(QString::fromUtf8("comboBox_11"));
        comboBox_11->setGeometry(QRect(108, 100, 81, 20));
        stackedWidget_2->addWidget(bufferPage);
        backgroundPage = new QWidget();
        backgroundPage->setObjectName(QString::fromUtf8("backgroundPage"));
        label_12 = new QLabel(backgroundPage);
        label_12->setObjectName(QString::fromUtf8("label_12"));
        label_12->setGeometry(QRect(10, 0, 91, 16));
        label_12->setFont(font);
        checkBox_4 = new QCheckBox(backgroundPage);
        checkBox_4->setObjectName(QString::fromUtf8("checkBox_4"));
        checkBox_4->setGeometry(QRect(10, 30, 151, 22));
        label_38 = new QLabel(backgroundPage);
        label_38->setObjectName(QString::fromUtf8("label_38"));
        label_38->setGeometry(QRect(30, 60, 30, 16));
        comboBox_12 = new QComboBox(backgroundPage);
        comboBox_12->setObjectName(QString::fromUtf8("comboBox_12"));
        comboBox_12->setGeometry(QRect(110, 60, 121, 20));
        label_39 = new QLabel(backgroundPage);
        label_39->setObjectName(QString::fromUtf8("label_39"));
        label_39->setGeometry(QRect(30, 90, 53, 16));
        spinBox_6 = new QSpinBox(backgroundPage);
        spinBox_6->setObjectName(QString::fromUtf8("spinBox_6"));
        spinBox_6->setGeometry(QRect(110, 90, 61, 20));
        spinBox_7 = new QSpinBox(backgroundPage);
        spinBox_7->setObjectName(QString::fromUtf8("spinBox_7"));
        spinBox_7->setGeometry(QRect(180, 90, 51, 20));
        label_40 = new QLabel(backgroundPage);
        label_40->setObjectName(QString::fromUtf8("label_40"));
        label_40->setGeometry(QRect(30, 120, 66, 16));
        horizontalSlider_4 = new QSlider(backgroundPage);
        horizontalSlider_4->setObjectName(QString::fromUtf8("horizontalSlider_4"));
        horizontalSlider_4->setGeometry(QRect(113, 120, 231, 19));
        horizontalSlider_4->setOrientation(Qt::Horizontal);
        label_41 = new QLabel(backgroundPage);
        label_41->setObjectName(QString::fromUtf8("label_41"));
        label_41->setGeometry(QRect(30, 150, 40, 16));
        comboBox_13 = new QComboBox(backgroundPage);
        comboBox_13->setObjectName(QString::fromUtf8("comboBox_13"));
        comboBox_13->setGeometry(QRect(110, 150, 121, 20));
        label_42 = new QLabel(backgroundPage);
        label_42->setObjectName(QString::fromUtf8("label_42"));
        label_42->setGeometry(QRect(30, 180, 60, 16));
        comboBox_14 = new QComboBox(backgroundPage);
        comboBox_14->setObjectName(QString::fromUtf8("comboBox_14"));
        comboBox_14->setGeometry(QRect(110, 180, 121, 20));
        label_43 = new QLabel(backgroundPage);
        label_43->setObjectName(QString::fromUtf8("label_43"));
        label_43->setGeometry(QRect(30, 210, 63, 16));
        spinBox_8 = new QSpinBox(backgroundPage);
        spinBox_8->setObjectName(QString::fromUtf8("spinBox_8"));
        spinBox_8->setGeometry(QRect(110, 210, 121, 20));
        stackedWidget_2->addWidget(backgroundPage);
        shadowPage = new QWidget();
        shadowPage->setObjectName(QString::fromUtf8("shadowPage"));
        label_13 = new QLabel(shadowPage);
        label_13->setObjectName(QString::fromUtf8("label_13"));
        label_13->setGeometry(QRect(10, 0, 101, 16));
        label_13->setFont(font);
        checkBox_5 = new QCheckBox(shadowPage);
        checkBox_5->setObjectName(QString::fromUtf8("checkBox_5"));
        checkBox_5->setGeometry(QRect(10, 30, 161, 22));
        label_37 = new QLabel(shadowPage);
        label_37->setObjectName(QString::fromUtf8("label_37"));
        label_37->setGeometry(QRect(30, 60, 56, 16));
        comboBox_15 = new QComboBox(shadowPage);
        comboBox_15->setObjectName(QString::fromUtf8("comboBox_15"));
        comboBox_15->setGeometry(QRect(110, 60, 91, 20));
        label_44 = new QLabel(shadowPage);
        label_44->setObjectName(QString::fromUtf8("label_44"));
        label_44->setGeometry(QRect(30, 90, 31, 16));
        spinBox_10 = new QSpinBox(shadowPage);
        spinBox_10->setObjectName(QString::fromUtf8("spinBox_10"));
        spinBox_10->setGeometry(QRect(110, 90, 91, 20));
        label_45 = new QLabel(shadowPage);
        label_45->setObjectName(QString::fromUtf8("label_45"));
        label_45->setGeometry(QRect(30, 120, 50, 16));
        spinBox_11 = new QSpinBox(shadowPage);
        spinBox_11->setObjectName(QString::fromUtf8("spinBox_11"));
        spinBox_11->setGeometry(QRect(110, 120, 91, 20));
        label_46 = new QLabel(shadowPage);
        label_46->setObjectName(QString::fromUtf8("label_46"));
        label_46->setGeometry(QRect(30, 150, 66, 16));
        horizontalSlider_5 = new QSlider(shadowPage);
        horizontalSlider_5->setObjectName(QString::fromUtf8("horizontalSlider_5"));
        horizontalSlider_5->setGeometry(QRect(110, 150, 241, 20));
        horizontalSlider_5->setOrientation(Qt::Horizontal);
        label_47 = new QLabel(shadowPage);
        label_47->setObjectName(QString::fromUtf8("label_47"));
        label_47->setGeometry(QRect(30, 180, 25, 16));
        spinBox_9 = new QSpinBox(shadowPage);
        spinBox_9->setObjectName(QString::fromUtf8("spinBox_9"));
        spinBox_9->setGeometry(QRect(110, 180, 91, 20));
        label_48 = new QLabel(shadowPage);
        label_48->setObjectName(QString::fromUtf8("label_48"));
        label_48->setGeometry(QRect(30, 210, 25, 16));
        comboBox_16 = new QComboBox(shadowPage);
        comboBox_16->setObjectName(QString::fromUtf8("comboBox_16"));
        comboBox_16->setGeometry(QRect(110, 210, 91, 20));
        stackedWidget_2->addWidget(shadowPage);
        listWidget_2 = new QListWidget(groupBox_3);
        new QListWidgetItem(listWidget_2);
        new QListWidgetItem(listWidget_2);
        new QListWidgetItem(listWidget_2);
        new QListWidgetItem(listWidget_2);
        new QListWidgetItem(listWidget_2);
        listWidget_2->setObjectName(QString::fromUtf8("listWidget_2"));
        listWidget_2->setGeometry(QRect(20, 150, 101, 261));
        label_8 = new QLabel(groupBox_3);
        label_8->setObjectName(QString::fromUtf8("label_8"));
        label_8->setGeometry(QRect(20, 110, 22, 16));
        label_29 = new QLabel(groupBox_3);
        label_29->setObjectName(QString::fromUtf8("label_29"));
        label_29->setGeometry(QRect(20, 20, 95, 16));
        comboBox_8 = new QComboBox(groupBox_3);
        comboBox_8->setObjectName(QString::fromUtf8("comboBox_8"));
        comboBox_8->setGeometry(QRect(130, 20, 69, 20));
        splitter_19 = new QSplitter(groupBox_3);
        splitter_19->setObjectName(QString::fromUtf8("splitter_19"));
        splitter_19->setGeometry(QRect(20, 50, 58, 16));
        splitter_19->setOrientation(Qt::Vertical);
        label_7 = new QLabel(splitter_19);
        label_7->setObjectName(QString::fromUtf8("label_7"));
        splitter_19->addWidget(label_7);
        textEdit = new QTextEdit(groupBox_3);
        textEdit->setObjectName(QString::fromUtf8("textEdit"));
        textEdit->setGeometry(QRect(130, 50, 361, 51));

        gridLayout_4->addWidget(groupBox_3, 0, 0, 1, 1);

        stackedWidget->addWidget(labelPage);
        diagramPage = new QWidget();
        diagramPage->setObjectName(QString::fromUtf8("diagramPage"));
        gridLayout_5 = new QGridLayout(diagramPage);
        gridLayout_5->setObjectName(QString::fromUtf8("gridLayout_5"));
        groupBox_4 = new QGroupBox(diagramPage);
        groupBox_4->setObjectName(QString::fromUtf8("groupBox_4"));
        checkBox_6 = new QCheckBox(groupBox_4);
        checkBox_6->setObjectName(QString::fromUtf8("checkBox_6"));
        checkBox_6->setGeometry(QRect(10, 30, 141, 22));
        label_14 = new QLabel(groupBox_4);
        label_14->setObjectName(QString::fromUtf8("label_14"));
        label_14->setGeometry(QRect(30, 60, 101, 17));
        comboBox_17 = new QComboBox(groupBox_4);
        comboBox_17->setObjectName(QString::fromUtf8("comboBox_17"));
        comboBox_17->setGeometry(QRect(120, 60, 91, 21));
        tabWidget = new QTabWidget(groupBox_4);
        tabWidget->setObjectName(QString::fromUtf8("tabWidget"));
        tabWidget->setGeometry(QRect(30, 90, 471, 201));
        Appearance = new QWidget();
        Appearance->setObjectName(QString::fromUtf8("Appearance"));
        pushButton_2 = new QPushButton(Appearance);
        pushButton_2->setObjectName(QString::fromUtf8("pushButton_2"));
        pushButton_2->setGeometry(QRect(20, 130, 61, 21));
        label_15 = new QLabel(Appearance);
        label_15->setObjectName(QString::fromUtf8("label_15"));
        label_15->setGeometry(QRect(20, 10, 66, 16));
        horizontalSlider_6 = new QSlider(Appearance);
        horizontalSlider_6->setObjectName(QString::fromUtf8("horizontalSlider_6"));
        horizontalSlider_6->setGeometry(QRect(100, 10, 311, 19));
        horizontalSlider_6->setOrientation(Qt::Horizontal);
        label_49 = new QLabel(Appearance);
        label_49->setObjectName(QString::fromUtf8("label_49"));
        label_49->setGeometry(QRect(20, 40, 45, 16));
        comboBox_18 = new QComboBox(Appearance);
        comboBox_18->setObjectName(QString::fromUtf8("comboBox_18"));
        comboBox_18->setGeometry(QRect(100, 40, 91, 20));
        label_50 = new QLabel(Appearance);
        label_50->setObjectName(QString::fromUtf8("label_50"));
        label_50->setGeometry(QRect(20, 70, 48, 16));
        comboBox_19 = new QComboBox(Appearance);
        comboBox_19->setObjectName(QString::fromUtf8("comboBox_19"));
        comboBox_19->setGeometry(QRect(100, 70, 91, 20));
        label_51 = new QLabel(Appearance);
        label_51->setObjectName(QString::fromUtf8("label_51"));
        label_51->setGeometry(QRect(20, 100, 54, 16));
        comboBox_20 = new QComboBox(Appearance);
        comboBox_20->setObjectName(QString::fromUtf8("comboBox_20"));
        comboBox_20->setGeometry(QRect(100, 100, 91, 20));
        tabWidget->addTab(Appearance, QString());
        Size = new QWidget();
        Size->setObjectName(QString::fromUtf8("Size"));
        checkBox_7 = new QCheckBox(Size);
        checkBox_7->setObjectName(QString::fromUtf8("checkBox_7"));
        checkBox_7->setGeometry(QRect(20, 10, 98, 22));
        spinBox_12 = new QSpinBox(Size);
        spinBox_12->setObjectName(QString::fromUtf8("spinBox_12"));
        spinBox_12->setGeometry(QRect(140, 10, 71, 21));
        tabWidget->addTab(Size, QString());
        Position = new QWidget();
        Position->setObjectName(QString::fromUtf8("Position"));
        checkBox_8 = new QCheckBox(Position);
        checkBox_8->setObjectName(QString::fromUtf8("checkBox_8"));
        checkBox_8->setGeometry(QRect(20, 80, 131, 22));
        splitter_57 = new QSplitter(Position);
        splitter_57->setObjectName(QString::fromUtf8("splitter_57"));
        splitter_57->setGeometry(QRect(40, 140, 94, 21));
        splitter_57->setOrientation(Qt::Horizontal);
        label_55 = new QLabel(splitter_57);
        label_55->setObjectName(QString::fromUtf8("label_55"));
        splitter_57->addWidget(label_55);
        comboBox_24 = new QComboBox(splitter_57);
        comboBox_24->setObjectName(QString::fromUtf8("comboBox_24"));
        splitter_57->addWidget(comboBox_24);
        splitter_58 = new QSplitter(Position);
        splitter_58->setObjectName(QString::fromUtf8("splitter_58"));
        splitter_58->setGeometry(QRect(40, 110, 93, 21));
        splitter_58->setOrientation(Qt::Horizontal);
        label_54 = new QLabel(splitter_58);
        label_54->setObjectName(QString::fromUtf8("label_54"));
        splitter_58->addWidget(label_54);
        comboBox_23 = new QComboBox(splitter_58);
        comboBox_23->setObjectName(QString::fromUtf8("comboBox_23"));
        splitter_58->addWidget(comboBox_23);
        label_52 = new QLabel(Position);
        label_52->setObjectName(QString::fromUtf8("label_52"));
        label_52->setGeometry(QRect(20, 10, 37, 16));
        comboBox_21 = new QComboBox(Position);
        comboBox_21->setObjectName(QString::fromUtf8("comboBox_21"));
        comboBox_21->setGeometry(QRect(70, 10, 91, 20));
        label_53 = new QLabel(Position);
        label_53->setObjectName(QString::fromUtf8("label_53"));
        label_53->setGeometry(QRect(20, 40, 41, 16));
        comboBox_22 = new QComboBox(Position);
        comboBox_22->setObjectName(QString::fromUtf8("comboBox_22"));
        comboBox_22->setGeometry(QRect(70, 40, 91, 20));
        tabWidget->addTab(Position, QString());
        listView = new QListView(groupBox_4);
        listView->setObjectName(QString::fromUtf8("listView"));
        listView->setGeometry(QRect(30, 330, 191, 81));
        listView_2 = new QListView(groupBox_4);
        listView_2->setObjectName(QString::fromUtf8("listView_2"));
        listView_2->setGeometry(QRect(280, 330, 191, 81));
        pushButton_3 = new QPushButton(groupBox_4);
        pushButton_3->setObjectName(QString::fromUtf8("pushButton_3"));
        pushButton_3->setGeometry(QRect(230, 350, 31, 27));
        pushButton_4 = new QPushButton(groupBox_4);
        pushButton_4->setObjectName(QString::fromUtf8("pushButton_4"));
        pushButton_4->setGeometry(QRect(230, 380, 31, 27));
        label_56 = new QLabel(groupBox_4);
        label_56->setObjectName(QString::fromUtf8("label_56"));
        label_56->setGeometry(QRect(30, 310, 131, 17));
        label_57 = new QLabel(groupBox_4);
        label_57->setObjectName(QString::fromUtf8("label_57"));
        label_57->setGeometry(QRect(280, 310, 131, 17));

        gridLayout_5->addWidget(groupBox_4, 0, 0, 1, 1);

        stackedWidget->addWidget(diagramPage);
        defaultStylePage = new QWidget();
        defaultStylePage->setObjectName(QString::fromUtf8("defaultStylePage"));
        gridLayout_6 = new QGridLayout(defaultStylePage);
        gridLayout_6->setObjectName(QString::fromUtf8("gridLayout_6"));
        groupBox_5 = new QGroupBox(defaultStylePage);
        groupBox_5->setObjectName(QString::fromUtf8("groupBox_5"));
        label_58 = new QLabel(groupBox_5);
        label_58->setObjectName(QString::fromUtf8("label_58"));
        label_58->setGeometry(QRect(20, 30, 111, 17));
        label_63 = new QLabel(groupBox_5);
        label_63->setObjectName(QString::fromUtf8("label_63"));
        label_63->setGeometry(QRect(20, 190, 67, 17));
        label_64 = new QLabel(groupBox_5);
        label_64->setObjectName(QString::fromUtf8("label_64"));
        label_64->setGeometry(QRect(30, 210, 101, 17));
        horizontalSlider_7 = new QSlider(groupBox_5);
        horizontalSlider_7->setObjectName(QString::fromUtf8("horizontalSlider_7"));
        horizontalSlider_7->setGeometry(QRect(100, 210, 331, 21));
        horizontalSlider_7->setOrientation(Qt::Horizontal);
        checkBox_9 = new QCheckBox(groupBox_5);
        checkBox_9->setObjectName(QString::fromUtf8("checkBox_9"));
        checkBox_9->setGeometry(QRect(30, 240, 181, 22));
        label_59 = new QLabel(groupBox_5);
        label_59->setObjectName(QString::fromUtf8("label_59"));
        label_59->setGeometry(QRect(30, 60, 33, 16));
        comboBox_25 = new QComboBox(groupBox_5);
        comboBox_25->setObjectName(QString::fromUtf8("comboBox_25"));
        comboBox_25->setGeometry(QRect(100, 60, 91, 20));
        label_62 = new QLabel(groupBox_5);
        label_62->setObjectName(QString::fromUtf8("label_62"));
        label_62->setGeometry(QRect(30, 150, 55, 16));
        comboBox_28 = new QComboBox(groupBox_5);
        comboBox_28->setObjectName(QString::fromUtf8("comboBox_28"));
        comboBox_28->setGeometry(QRect(100, 150, 91, 20));
        label_60 = new QLabel(groupBox_5);
        label_60->setObjectName(QString::fromUtf8("label_60"));
        label_60->setGeometry(QRect(30, 90, 19, 16));
        comboBox_26 = new QComboBox(groupBox_5);
        comboBox_26->setObjectName(QString::fromUtf8("comboBox_26"));
        comboBox_26->setGeometry(QRect(100, 90, 91, 20));
        label_61 = new QLabel(groupBox_5);
        label_61->setObjectName(QString::fromUtf8("label_61"));
        label_61->setGeometry(QRect(30, 120, 16, 16));
        comboBox_27 = new QComboBox(groupBox_5);
        comboBox_27->setObjectName(QString::fromUtf8("comboBox_27"));
        comboBox_27->setGeometry(QRect(100, 120, 91, 20));

        gridLayout_6->addWidget(groupBox_5, 0, 1, 1, 1);

        stackedWidget->addWidget(defaultStylePage);
        layoutWidget = new QWidget(LayerProperties);
        layoutWidget->setObjectName(QString::fromUtf8("layoutWidget"));
        layoutWidget->setGeometry(QRect(140, 460, 511, 25));
        horizontalLayout_7 = new QHBoxLayout(layoutWidget);
        horizontalLayout_7->setObjectName(QString::fromUtf8("horizontalLayout_7"));
        horizontalLayout_7->setContentsMargins(0, 0, 0, 0);
        horizontalSpacer_5 = new QSpacerItem(258, 20, QSizePolicy::Expanding, QSizePolicy::Minimum);

        horizontalLayout_7->addItem(horizontalSpacer_5);

        buttonBox = new QDialogButtonBox(layoutWidget);
        buttonBox->setObjectName(QString::fromUtf8("buttonBox"));
        buttonBox->setOrientation(Qt::Horizontal);
        buttonBox->setStandardButtons(QDialogButtonBox::Cancel|QDialogButtonBox::Ok);

        horizontalLayout_7->addWidget(buttonBox);


        retranslateUi(LayerProperties);
        QObject::connect(buttonBox, SIGNAL(accepted()), LayerProperties, SLOT(accept()));
        QObject::connect(buttonBox, SIGNAL(rejected()), LayerProperties, SLOT(reject()));
        QObject::connect(listWidget, SIGNAL(currentRowChanged(int)), stackedWidget, SLOT(setCurrentIndex(int)));
        QObject::connect(listWidget_2, SIGNAL(currentRowChanged(int)), stackedWidget_2, SLOT(setCurrentIndex(int)));

        stackedWidget->setCurrentIndex(0);
        stackedWidget_2->setCurrentIndex(4);
        tabWidget->setCurrentIndex(2);


        QMetaObject::connectSlotsByName(LayerProperties);
    } // setupUi

    void retranslateUi(QDialog *LayerProperties)
    {
        LayerProperties->setWindowTitle(QApplication::translate("LayerProperties", "Layer Properties", 0, QApplication::UnicodeUTF8));

        const bool __sortingEnabled = listWidget->isSortingEnabled();
        listWidget->setSortingEnabled(false);
        QListWidgetItem *___qlistwidgetitem = listWidget->item(0);
        ___qlistwidgetitem->setText(QApplication::translate("LayerProperties", "General", 0, QApplication::UnicodeUTF8));
        QListWidgetItem *___qlistwidgetitem1 = listWidget->item(1);
        ___qlistwidgetitem1->setText(QApplication::translate("LayerProperties", "Style", 0, QApplication::UnicodeUTF8));
        QListWidgetItem *___qlistwidgetitem2 = listWidget->item(2);
        ___qlistwidgetitem2->setText(QApplication::translate("LayerProperties", "Label", 0, QApplication::UnicodeUTF8));
        QListWidgetItem *___qlistwidgetitem3 = listWidget->item(3);
        ___qlistwidgetitem3->setText(QApplication::translate("LayerProperties", "Diagram", 0, QApplication::UnicodeUTF8));
        QListWidgetItem *___qlistwidgetitem4 = listWidget->item(4);
        ___qlistwidgetitem4->setText(QApplication::translate("LayerProperties", "Default Style", 0, QApplication::UnicodeUTF8));
        listWidget->setSortingEnabled(__sortingEnabled);

        groupBox->setTitle(QApplication::translate("LayerProperties", "General", 0, QApplication::UnicodeUTF8));
        label->setText(QApplication::translate("LayerProperties", "Layer Name", 0, QApplication::UnicodeUTF8));
        label_2->setText(QApplication::translate("LayerProperties", "Layer Source", 0, QApplication::UnicodeUTF8));
        label_25->setText(QApplication::translate("LayerProperties", "Layer Type", 0, QApplication::UnicodeUTF8));
        label_26->setText(QApplication::translate("LayerProperties", "Coordinate Reference System", 0, QApplication::UnicodeUTF8));
        lineEdit_5->setText(QApplication::translate("LayerProperties", "EPSG:4326 - WGS 84", 0, QApplication::UnicodeUTF8));
        checkBox->setText(QApplication::translate("LayerProperties", "Scale dependent visibility", 0, QApplication::UnicodeUTF8));
        label_27->setText(QApplication::translate("LayerProperties", "Maximum (inclusive)", 0, QApplication::UnicodeUTF8));
        label_28->setText(QApplication::translate("LayerProperties", "Minimum (exclusive)", 0, QApplication::UnicodeUTF8));
        groupBox_2->setTitle(QApplication::translate("LayerProperties", "Style", 0, QApplication::UnicodeUTF8));
        label_3->setText(QApplication::translate("LayerProperties", "Fill Sample", 0, QApplication::UnicodeUTF8));
        label_4->setText(QApplication::translate("LayerProperties", "Transparancy", 0, QApplication::UnicodeUTF8));
        label_5->setText(QApplication::translate("LayerProperties", "Colour", 0, QApplication::UnicodeUTF8));
        label_6->setText(QApplication::translate("LayerProperties", "Contour", 0, QApplication::UnicodeUTF8));
        groupBox_3->setTitle(QApplication::translate("LayerProperties", "Label", 0, QApplication::UnicodeUTF8));
        pushButton->setText(QApplication::translate("LayerProperties", "set", 0, QApplication::UnicodeUTF8));
        label_9->setText(QApplication::translate("LayerProperties", "Text Style", 0, QApplication::UnicodeUTF8));
        label_16->setText(QApplication::translate("LayerProperties", "Font", 0, QApplication::UnicodeUTF8));
        label_17->setText(QApplication::translate("LayerProperties", "Style", 0, QApplication::UnicodeUTF8));
        label_18->setText(QApplication::translate("LayerProperties", "Size", 0, QApplication::UnicodeUTF8));
        label_19->setText(QApplication::translate("LayerProperties", "Colour", 0, QApplication::UnicodeUTF8));
        label_20->setText(QApplication::translate("LayerProperties", "Transparency", 0, QApplication::UnicodeUTF8));
        label_21->setText(QApplication::translate("LayerProperties", "Type Case", 0, QApplication::UnicodeUTF8));
        label_23->setText(QApplication::translate("LayerProperties", "Letter", 0, QApplication::UnicodeUTF8));
        label_24->setText(QApplication::translate("LayerProperties", "word", 0, QApplication::UnicodeUTF8));
        label_22->setText(QApplication::translate("LayerProperties", "Spacing", 0, QApplication::UnicodeUTF8));
        label_10->setText(QApplication::translate("LayerProperties", "Text Formatting", 0, QApplication::UnicodeUTF8));
        label_30->setText(QApplication::translate("LayerProperties", "Multiple Line", 0, QApplication::UnicodeUTF8));
        checkBox_2->setText(QApplication::translate("LayerProperties", "Formatted number", 0, QApplication::UnicodeUTF8));
        label_31->setText(QApplication::translate("LayerProperties", "Line Height", 0, QApplication::UnicodeUTF8));
        label_32->setText(QApplication::translate("LayerProperties", "Alignment", 0, QApplication::UnicodeUTF8));
        label_33->setText(QApplication::translate("LayerProperties", "Decimal places", 0, QApplication::UnicodeUTF8));
        label_11->setText(QApplication::translate("LayerProperties", "Text Buffer", 0, QApplication::UnicodeUTF8));
        checkBox_3->setText(QApplication::translate("LayerProperties", "Draw text buffer", 0, QApplication::UnicodeUTF8));
        label_34->setText(QApplication::translate("LayerProperties", "Size", 0, QApplication::UnicodeUTF8));
        label_36->setText(QApplication::translate("LayerProperties", "Transparency", 0, QApplication::UnicodeUTF8));
        label_35->setText(QApplication::translate("LayerProperties", "Color", 0, QApplication::UnicodeUTF8));
        label_12->setText(QApplication::translate("LayerProperties", "Background", 0, QApplication::UnicodeUTF8));
        checkBox_4->setText(QApplication::translate("LayerProperties", "Draw Background", 0, QApplication::UnicodeUTF8));
        label_38->setText(QApplication::translate("LayerProperties", "Shape", 0, QApplication::UnicodeUTF8));
        label_39->setText(QApplication::translate("LayerProperties", "Offset X, Y", 0, QApplication::UnicodeUTF8));
        label_40->setText(QApplication::translate("LayerProperties", "Transparency", 0, QApplication::UnicodeUTF8));
        label_41->setText(QApplication::translate("LayerProperties", "Fill Color", 0, QApplication::UnicodeUTF8));
        label_42->setText(QApplication::translate("LayerProperties", "Border Color", 0, QApplication::UnicodeUTF8));
        label_43->setText(QApplication::translate("LayerProperties", "Border Width", 0, QApplication::UnicodeUTF8));
        label_13->setText(QApplication::translate("LayerProperties", "Drop Shadow", 0, QApplication::UnicodeUTF8));
        checkBox_5->setText(QApplication::translate("LayerProperties", "Draw drop shadow", 0, QApplication::UnicodeUTF8));
        label_37->setText(QApplication::translate("LayerProperties", "Draw under", 0, QApplication::UnicodeUTF8));
        label_44->setText(QApplication::translate("LayerProperties", "Offset", 0, QApplication::UnicodeUTF8));
        label_45->setText(QApplication::translate("LayerProperties", "Blur radius", 0, QApplication::UnicodeUTF8));
        label_46->setText(QApplication::translate("LayerProperties", "Transparency", 0, QApplication::UnicodeUTF8));
        label_47->setText(QApplication::translate("LayerProperties", "Scale", 0, QApplication::UnicodeUTF8));
        label_48->setText(QApplication::translate("LayerProperties", "Color", 0, QApplication::UnicodeUTF8));

        const bool __sortingEnabled1 = listWidget_2->isSortingEnabled();
        listWidget_2->setSortingEnabled(false);
        QListWidgetItem *___qlistwidgetitem5 = listWidget_2->item(0);
        ___qlistwidgetitem5->setText(QApplication::translate("LayerProperties", "Text", 0, QApplication::UnicodeUTF8));
        QListWidgetItem *___qlistwidgetitem6 = listWidget_2->item(1);
        ___qlistwidgetitem6->setText(QApplication::translate("LayerProperties", "Formating", 0, QApplication::UnicodeUTF8));
        QListWidgetItem *___qlistwidgetitem7 = listWidget_2->item(2);
        ___qlistwidgetitem7->setText(QApplication::translate("LayerProperties", "Buffer", 0, QApplication::UnicodeUTF8));
        QListWidgetItem *___qlistwidgetitem8 = listWidget_2->item(3);
        ___qlistwidgetitem8->setText(QApplication::translate("LayerProperties", "Background", 0, QApplication::UnicodeUTF8));
        QListWidgetItem *___qlistwidgetitem9 = listWidget_2->item(4);
        ___qlistwidgetitem9->setText(QApplication::translate("LayerProperties", "Shadow", 0, QApplication::UnicodeUTF8));
        listWidget_2->setSortingEnabled(__sortingEnabled1);

        label_8->setText(QApplication::translate("LayerProperties", "Text", 0, QApplication::UnicodeUTF8));
        label_29->setText(QApplication::translate("LayerProperties", "Label this layer with", 0, QApplication::UnicodeUTF8));
        label_7->setText(QApplication::translate("LayerProperties", "Text sample", 0, QApplication::UnicodeUTF8));
        groupBox_4->setTitle(QApplication::translate("LayerProperties", "Diagram", 0, QApplication::UnicodeUTF8));
        checkBox_6->setText(QApplication::translate("LayerProperties", "Display diagram", 0, QApplication::UnicodeUTF8));
        label_14->setText(QApplication::translate("LayerProperties", "Diagram type", 0, QApplication::UnicodeUTF8));
        pushButton_2->setText(QApplication::translate("LayerProperties", "Font...", 0, QApplication::UnicodeUTF8));
        label_15->setText(QApplication::translate("LayerProperties", "Transparancy", 0, QApplication::UnicodeUTF8));
        label_49->setText(QApplication::translate("LayerProperties", "Line color", 0, QApplication::UnicodeUTF8));
        label_50->setText(QApplication::translate("LayerProperties", "Line width", 0, QApplication::UnicodeUTF8));
        label_51->setText(QApplication::translate("LayerProperties", "Start Angel", 0, QApplication::UnicodeUTF8));
        tabWidget->setTabText(tabWidget->indexOf(Appearance), QApplication::translate("LayerProperties", "Appearance", 0, QApplication::UnicodeUTF8));
        checkBox_7->setText(QApplication::translate("LayerProperties", "Fixed size", 0, QApplication::UnicodeUTF8));
        tabWidget->setTabText(tabWidget->indexOf(Size), QApplication::translate("LayerProperties", "Size", 0, QApplication::UnicodeUTF8));
        checkBox_8->setText(QApplication::translate("LayerProperties", "Data defined position", 0, QApplication::UnicodeUTF8));
        label_55->setText(QApplication::translate("LayerProperties", "y", 0, QApplication::UnicodeUTF8));
        label_54->setText(QApplication::translate("LayerProperties", "x", 0, QApplication::UnicodeUTF8));
        label_52->setText(QApplication::translate("LayerProperties", "Position", 0, QApplication::UnicodeUTF8));
        label_53->setText(QApplication::translate("LayerProperties", "Distance", 0, QApplication::UnicodeUTF8));
        tabWidget->setTabText(tabWidget->indexOf(Position), QApplication::translate("LayerProperties", "Position", 0, QApplication::UnicodeUTF8));
        pushButton_3->setText(QApplication::translate("LayerProperties", "+", 0, QApplication::UnicodeUTF8));
        pushButton_4->setText(QApplication::translate("LayerProperties", "-", 0, QApplication::UnicodeUTF8));
        label_56->setText(QApplication::translate("LayerProperties", "Available atribute", 0, QApplication::UnicodeUTF8));
        label_57->setText(QApplication::translate("LayerProperties", "Assigned atribute", 0, QApplication::UnicodeUTF8));
        groupBox_5->setTitle(QApplication::translate("LayerProperties", "Default Style", 0, QApplication::UnicodeUTF8));
        label_58->setText(QApplication::translate("LayerProperties", "Default Symbol", 0, QApplication::UnicodeUTF8));
        label_63->setText(QApplication::translate("LayerProperties", "Option", 0, QApplication::UnicodeUTF8));
        label_64->setText(QApplication::translate("LayerProperties", "Transparency", 0, QApplication::UnicodeUTF8));
        checkBox_9->setText(QApplication::translate("LayerProperties", "Assigned random color to symbol", 0, QApplication::UnicodeUTF8));
        label_59->setText(QApplication::translate("LayerProperties", "Marker", 0, QApplication::UnicodeUTF8));
        label_62->setText(QApplication::translate("LayerProperties", "Color Ramp", 0, QApplication::UnicodeUTF8));
        label_60->setText(QApplication::translate("LayerProperties", "Line", 0, QApplication::UnicodeUTF8));
        label_61->setText(QApplication::translate("LayerProperties", "Fill", 0, QApplication::UnicodeUTF8));
    } // retranslateUi

};

namespace Ui {
    class LayerProperties: public Ui_LayerProperties {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_LAYERPROPERTIES_H
